env:
  rclone_config: ENCRYPTED[237e7dbd3c9d6d4f44c6e746924664ee27d9000fa7707038f2b61fb5071b2db49c56ae487ee532b9b688560ec3ede091]
  bot_token: ENCRYPTED[3f3ccb1a9c15a15da2f8388f184ad2c0a966baefb59167b8e5fb32d94567d1aab137a1724d186c5c9a2d63faa1f249a2]
  channel_id: ENCRYPTED[b7aa15b821b8d52e040dd27c36a3ee36c353add68d68711a1798c4cdbdf9d3cab1babb7565ff9546d2cc728ef9b202ce]


task:
  name: epaper_today_daily
  timeout_in: 120m
  only_if: $CIRRUS_CRON == "daily"
  container:
    image: python:latest
  initialize_script:
    - apt update
    - apt install --fix-missing -y rclone fd-find
    - ln -s $(which fdfind) /usr/bin/fd
    - pip install -r requirements.txt
    - mkdir -p /root/.config/rclone
    - mkdir -p /tmp/epothi
    - touch /tmp/failed.txt
    - touch /root/.config/rclone/rclone.conf
    - echo "${rclone_config}" >> /root/.config/rclone/rclone.conf
    - rclone tree 'gdrive:' | tee /tmp/gdrive.txt
    - cat /tmp/gdrive.txt
  epaper_daily_script:
    - source .env
    - shopt -s globstar
    - epaper_today
    - telegram_up_current $bot_token $channel_id
